<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" 
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="text" omit-xml-declaration="yes"/>

<xsl:param name="current-date"/>

<xsl:template match="/plane">
/*****************************************************************************
** AUTOGENERATED ON <xsl:value-of select="$current-date"/> - DO NOT EDIT 
******************************************************************************
** AIRCRAFT : <xsl:value-of select="@name"/>
******************************************************************************
** File     : SimulatorPanel.h
** Project  : Flight Gear Flight Simulator to Saitek Switch Panel Interface
** Author   : Dave Attwood dave@attwoods.org.uk
** Copyright: (c) David Attwood <xsl:value-of select="$current-year"/>
** License  : GPL V3 or later
******************************************************************************
** AUTOGENERATED ON <xsl:value-of select="$current-date"/> - DO NOT EDIT 
******************************************************************************
** */
#ifndef SIMULATORPANEL_H_
#define SIMULATORPANEL_H_

#include "SwitchFunctions.h"

FGIF switchDef[] = {
   	<xsl:apply-templates select="switch"/>
};

int switchValues [sizeof(switchDef)/sizeof(FGIF)];  /* holds 'last used' settings */
	
	<xsl:apply-templates select="gear"/>
	<xsl:apply-templates select="magnetos"/>
	<xsl:apply-templates select="magswitch"/>
	<xsl:apply-templates select="starter"/>	
   <xsl:apply-templates select="gear-retarget"/>

#endif	/* SIMULATORPANEL_H */

</xsl:template>
 
 <xsl:template match="switch">
    {<xsl:value-of select="@name"/>, "<xsl:value-of select="normalize-space(.)"/>"},</xsl:template>

<xsl:template match="magnetos">
char * magnetoSim = "<xsl:value-of select="normalize-space(.)"/>";
int magnetoValue;  /* holds 'last used' setting */
int magnetoMap [5] = { MAGOFF, MAGR, MAGL, MAGBOTH, MAGSTART};
</xsl:template>

<xsl:template match="starter">
char * magStarter = "<xsl:value-of select="normalize-space(.)"/>";
</xsl:template>

<xsl:template match="gear">
#define GEARRETRACTS</xsl:template>

<xsl:template match="gear-retarget">
#define GEARRETARGET
char * geartarget = "<xsl:value-of select="normalize-space(.)"/>";
</xsl:template>

</xsl:stylesheet>
